use md5;

#[derive(Clone, Default)]
pub struct ValueRecipient {
    pub name: String,
    pub recipient_type: String,
    pub address: String,
    pub split: i32,
    pub fee: bool,
    pub custom_key: Option<String>,
    pub custom_value: Option<String>,
}

pub struct ParserState {
    // Channel-level flags and fields
    pub in_channel: bool,
    pub in_channel_image: bool,
    pub in_channel_itunes_owner: bool,
    pub in_channel_podcast_locked: bool,
    pub in_channel_podcast_funding: bool,
    pub in_standard_category: bool,
    pub channel_title: String,
    pub channel_link: String,
    pub channel_description: String,
    pub channel_itunes_summary: String,
    pub channel_language: String,
    pub channel_generator: String,
    pub channel_itunes_author: String,
    pub channel_itunes_owner_name: String,
    pub channel_itunes_owner_email: String,
    pub channel_itunes_type: String,
    pub channel_itunes_new_feed_url: String,
    pub channel_explicit: i32,
    pub channel_itunes_image: String,
    pub channel_image: String,
    pub channel_podcast_guid: String,
    pub channel_podcast_locked: i32,
    pub channel_podcast_owner: String,
    pub channel_podcast_funding_url: String,
    pub channel_podcast_funding_text: String,
    pub pubsub_hub_url: String,
    pub pubsub_self_url: String,
    pub channel_categories: Vec<String>,
    pub channel_categories_raw: Vec<String>,
    pub channel_value_pending: Option<(i32, String)>,
    pub channel_value_has_lightning: bool,

    // Item-level flags and fields
    pub in_item: bool,
    pub item_written: bool,
    pub current_element: String,
    pub title: String,
    pub itunes_title: String,
    pub link: String,
    pub description: String,
    pub itunes_summary: String,
    pub content_encoded: String,
    pub pub_date: String,
    pub guid: String,
    pub itunes_duration: String,
    pub itunes_episode: String,
    pub itunes_season: String,
    pub itunes_episode_type: String,
    pub itunes_explicit: i32,
    pub itunes_image: String,
    pub item_image: String,
    pub in_item_image: bool,
    pub item_has_valid_enclosure: bool,
    pub enclosure_url: String,
    pub enclosure_length: String,
    pub enclosure_type: String,
    pub podcast_funding_url: String,
    pub podcast_funding_text: String,
    pub in_podcast_funding: bool,
    pub current_transcript_url: String,
    pub current_transcript_type: String,
    pub in_podcast_transcript: bool,
    pub current_chapter_url: String,
    pub current_chapter_type: String,
    pub in_podcast_chapters: bool,
    pub current_soundbite_title: String,
    pub current_soundbite_start: String,
    pub current_soundbite_duration: String,
    pub in_podcast_soundbite: bool,
    pub current_person_name: String,
    pub current_person_role: String,
    pub current_person_group: String,
    pub current_person_img: String,
    pub current_person_href: String,
    pub in_podcast_person: bool,
    pub item_value_pending: Option<(i32, String)>,
    pub item_value_has_lightning: bool,
    pub value_recipients: Vec<ValueRecipient>,
    pub value_model_type: String,
    pub value_model_method: String,
    pub value_model_suggested: String,
    pub in_podcast_value: bool,
    pub content: String,

    // Item metrics
    pub item_pubdates: Vec<i64>,
    pub item_count: i32,
    pub newest_item_pubdate: Option<i64>,
    pub oldest_item_pubdate: Option<i64>,
    pub item_hash: md5::Context,
}

impl Default for ParserState {
    fn default() -> Self {
        Self {
            in_channel: false,
            in_channel_image: false,
            in_channel_itunes_owner: false,
            in_channel_podcast_locked: false,
            in_channel_podcast_funding: false,
            in_standard_category: false,
            channel_title: String::new(),
            channel_link: String::new(),
            channel_description: String::new(),
            channel_itunes_summary: String::new(),
            channel_language: String::new(),
            channel_generator: String::new(),
            channel_itunes_author: String::new(),
            channel_itunes_owner_name: String::new(),
            channel_itunes_owner_email: String::new(),
            channel_itunes_type: String::new(),
            channel_itunes_new_feed_url: String::new(),
            channel_explicit: 0,
            channel_itunes_image: String::new(),
            channel_image: String::new(),
            channel_podcast_guid: String::new(),
            channel_podcast_locked: 0,
            channel_podcast_owner: String::new(),
            channel_podcast_funding_url: String::new(),
            channel_podcast_funding_text: String::new(),
            pubsub_hub_url: String::new(),
            pubsub_self_url: String::new(),
            channel_categories: Vec::new(),
            channel_categories_raw: Vec::new(),
            channel_value_pending: None,
            channel_value_has_lightning: false,
            in_item: false,
            item_written: false,
            current_element: String::new(),
            title: String::new(),
            itunes_title: String::new(),
            link: String::new(),
            description: String::new(),
            itunes_summary: String::new(),
            content_encoded: String::new(),
            pub_date: String::new(),
            guid: String::new(),
            itunes_duration: String::new(),
            itunes_episode: String::new(),
            itunes_season: String::new(),
            itunes_episode_type: String::new(),
            itunes_explicit: 0,
            itunes_image: String::new(),
            item_image: String::new(),
            in_item_image: false,
            item_has_valid_enclosure: false,
            enclosure_url: String::new(),
            enclosure_length: String::new(),
            enclosure_type: String::new(),
            podcast_funding_url: String::new(),
            podcast_funding_text: String::new(),
            in_podcast_funding: false,
            current_transcript_url: String::new(),
            current_transcript_type: String::new(),
            in_podcast_transcript: false,
            current_chapter_url: String::new(),
            current_chapter_type: String::new(),
            in_podcast_chapters: false,
            current_soundbite_title: String::new(),
            current_soundbite_start: String::new(),
            current_soundbite_duration: String::new(),
            in_podcast_soundbite: false,
            current_person_name: String::new(),
            current_person_role: String::new(),
            current_person_group: String::new(),
            current_person_img: String::new(),
            current_person_href: String::new(),
            in_podcast_person: false,
            item_value_pending: None,
            item_value_has_lightning: false,
            value_recipients: Vec::new(),
            value_model_type: String::new(),
            value_model_method: String::new(),
            value_model_suggested: String::new(),
            in_podcast_value: false,
            item_pubdates: Vec::new(),
            item_count: 0,
            newest_item_pubdate: None,
            oldest_item_pubdate: None,
            item_hash: md5::Context::new(),
            content: String::new(),
        }
    }
}
